action_values: [0, 30, 60, 90]
activation: relu
batch_size: 128
clip_range: 0.3
delta: 0.05
dim_hidden_layers: [32, 32]
ent_coef: 0.001
filename: data_price_uni_h_time.csv
gae_lambda: 0.9999
gamma: 0.99
gas_fee: 5
grid: [ent_coef, gamma, clip_range]
hyperparameters:
  action_values:
  - - [0, 5, 10, 15, 20]
    - [0, 10, 20, 30]
    - [0, 30, 60, 90]
    - [0, 50, 100, 150]
  - cat
  activation:
  - [relu, tanh]
  - cat
  clip_range:
  - [0.1, 0.2, 0.3]
  - cat
  dim_hidden_layers:
  - - [32, 32]
    - [64, 64]
    - [128, 128]
    - [64, 32]
    - [128, 64]
    - [256, 128]
    - [128, 64, 32]
    - [256, 128, 64]
  - cat
  ent_coef:
  - [1.0e-05, 0.01, 0.001]
  - cat
  gamma:
  - [0.99, 0.999, 0.9999]
  - cat
  learning_rate:
  - [0.001, 0.0003, 0.0001]
  - cat
learning_rate: 0.001
ma_window: 10
model_name: ppo_custom_env_20241001_1
model_to_load: ppo_custom_env_20241001
n_trials: 10
num_epochs: 5
pct_split: 0.9
random_sampler: false
seed: 42
target_kl: 0.3
total_timesteps: 3000000
total_timesteps_1: 300000
train_model: false
vf_coef: 0.1
x: 10
